import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { lstatSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { FileRuntimeStore, RuntimeRepository } from "./persistence.ts";
import { reconcileInstitutionalKnowledge } from "./institutional-knowledge-reconciliation-service.ts";
import type { InstitutionalKnowledgeApplication, InstitutionalKnowledgeProposal, InstitutionalKnowledgeReview } from "./types.ts";

const digest = (value: string) => createHash("sha256").update(value).digest("hex");
const workspace = mkdtempSync(path.join(tmpdir(), "novara-knowledge-application-")); const vault = path.join(workspace, "Novara"); const target = path.join(vault, "Company", "Vision.md");
mkdirSync(path.dirname(target), { recursive: true }); mkdirSync(path.join(vault, "Strategy"), { recursive: true }); writeFileSync(target, "baseline", "utf8");
const manifest = (folder = vault): string[] => readdirSync(folder, { withFileTypes: true }).flatMap((entry) => { const full = path.join(folder, entry.name); const stat = lstatSync(full); return stat.isSymbolicLink() ? [`${entry.name}:link`] : entry.isDirectory() ? manifest(full).map((child) => `${entry.name}/${child}`) : [`${entry.name}:${digest(readFileSync(full, "utf8"))}`]; }).sort();
const proposal: InstitutionalKnowledgeProposal = { proposalId: "knowledge-proposal", proposerType: "human", proposerId: "guido", targetPath: "Company/Vision.md", baseContentHash: digest("baseline"), proposedContent: "proposed", rationale: "test", evidenceReferences: [], createdAt: "2026-08-14T00:00:00.000Z" };
const approved: InstitutionalKnowledgeReview = { reviewId: "review", proposalId: proposal.proposalId, reviewerId: "guido", decision: "approved", reviewedAt: proposal.createdAt };
const app = (status: InstitutionalKnowledgeApplication["status"], id = "application"): InstitutionalKnowledgeApplication => ({ applicationId: id, proposalId: proposal.proposalId, status, createdAt: proposal.createdAt, updatedAt: proposal.createdAt });
const setup = (review: "approved" | "rejected" | undefined) => { const root = mkdtempSync(path.join(tmpdir(), "novara-knowledge-runtime-")); const repo = new RuntimeRepository(new FileRuntimeStore(root)); repo.createInstitutionalKnowledgeProposal(proposal); if (review) repo.createInstitutionalKnowledgeReview({ ...approved, decision: review }); return repo; };
const initialManifest = manifest(); const cwd = process.cwd(); process.chdir(workspace);
assert.equal(setup(undefined).claimInstitutionalKnowledgeApplication(app("claimed")), undefined); assert.equal(setup("rejected").claimInstitutionalKnowledgeApplication(app("claimed")), undefined);
const repo = setup("approved"); assert.ok(repo.claimInstitutionalKnowledgeApplication(app("claimed"))); assert.equal(repo.claimInstitutionalKnowledgeApplication(app("claimed", "duplicate")), undefined); assert.deepEqual(manifest(), initialManifest);
const concurrentRoot = mkdtempSync(path.join(tmpdir(), "novara-knowledge-concurrent-")); const seed = new RuntimeRepository(new FileRuntimeStore(concurrentRoot)); seed.createInstitutionalKnowledgeProposal(proposal); seed.createInstitutionalKnowledgeReview(approved); const [one, two] = await Promise.all([Promise.resolve(new RuntimeRepository(new FileRuntimeStore(concurrentRoot)).claimInstitutionalKnowledgeApplication(app("claimed"))), Promise.resolve(new RuntimeRepository(new FileRuntimeStore(concurrentRoot)).claimInstitutionalKnowledgeApplication(app("claimed", "other")))]); assert.equal([one, two].filter(Boolean).length, 1); assert.ok(new RuntimeRepository(new FileRuntimeStore(concurrentRoot)).getInstitutionalKnowledgeApplicationByProposal(proposal.proposalId));
const statuses: InstitutionalKnowledgeApplication["status"][] = ["pending", "claimed", "applying", "applied", "conflict", "failed", "unknown-result"]; const allowed: Record<InstitutionalKnowledgeApplication["status"], InstitutionalKnowledgeApplication["status"][]> = { pending: ["claimed"], claimed: ["applying"], applying: ["applied", "conflict", "failed", "unknown-result"], applied: [], conflict: [], failed: [], "unknown-result": [] };
for (const source of statuses.filter((status) => status !== "pending")) for (const destination of statuses) { const r = setup("approved"); r.claimInstitutionalKnowledgeApplication(app("claimed")); if (source === "applying" || ["applied", "conflict", "failed", "unknown-result"].includes(source)) r.transitionInstitutionalKnowledgeApplication("application", "claimed", app("applying")); if (["applied", "conflict", "failed", "unknown-result"].includes(source)) r.transitionInstitutionalKnowledgeApplication("application", "applying", app(source)); const before = r.getInstitutionalKnowledgeApplicationByProposal(proposal.proposalId); const result = r.transitionInstitutionalKnowledgeApplication("application", source, app(destination)); if (allowed[source].includes(destination)) assert.ok(result); else { assert.equal(result, undefined); assert.deepEqual(r.getInstitutionalKnowledgeApplicationByProposal(proposal.proposalId), before); } }
{ const r = setup("approved"); assert.ok(r.claimInstitutionalKnowledgeApplication(app("claimed")), "claim is the atomic pending-to-claimed transition"); assert.equal(r.transitionInstitutionalKnowledgeApplication("application", "pending", app("claimed")), undefined); }
for (const [content, expected, application] of [["baseline", "not-applied", undefined], ["proposed", "applied", undefined], ["third", "conflict", undefined], ["third", "unknown-result", app("unknown-result")], ["baseline", "not-applied", app("unknown-result")], ["proposed", "applied", app("unknown-result")]] as const) { writeFileSync(target, content, "utf8"); assert.equal(reconcileInstitutionalKnowledge(proposal, application).status, expected); }
for (const bad of ["../x.md", path.resolve(target), ".obsidian/x.md", ".git/x.md", ".novara/x.md", "node_modules/x.md", "Other/x.md", "Company/Vision.txt", "Company/Missing.md"]) { assert.throws(() => reconcileInstitutionalKnowledge({ ...proposal, targetPath: bad }, undefined)); }
const outside = path.join(workspace, "outside"); mkdirSync(outside); writeFileSync(path.join(outside, "outside.md"), "outside", "utf8"); try { symlinkSync(outside, path.join(vault, "Strategy", "escape"), "junction"); } catch (error) { throw new Error(`Genuine junction fixture unavailable: ${(error as Error).code}`); } const escapeManifest = manifest(); assert.throws(() => reconcileInstitutionalKnowledge({ ...proposal, targetPath: "Strategy/escape/outside.md" }, undefined)); assert.equal(readFileSync(path.join(outside, "outside.md"), "utf8"), "outside"); assert.deepEqual(manifest(), escapeManifest);
process.chdir(cwd); console.log("Institutional knowledge application tests passed.");
